// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF37L45QGvIQVvTvqdf44KpDAFbWAwhNM',
    appId: '1:733817369426:web:f5231ce252e3da1dc6008b',
    messagingSenderId: '733817369426',
    projectId: 'store-app-42487',
    authDomain: 'store-app-42487.firebaseapp.com',
    storageBucket: 'store-app-42487.appspot.com',
    measurementId: 'G-51SVREF3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFg5762igzEfDM6P-eaXb3EBz6J4hCrmw',
    appId: '1:733817369426:android:759dd036e2d25d16c6008b',
    messagingSenderId: '733817369426',
    projectId: 'store-app-42487',
    storageBucket: 'store-app-42487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gQDwypC7PfL_eZbOCsPeedk1Sdo7m4g',
    appId: '1:733817369426:ios:3a7e8ab58206972fc6008b',
    messagingSenderId: '733817369426',
    projectId: 'store-app-42487',
    storageBucket: 'store-app-42487.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6gQDwypC7PfL_eZbOCsPeedk1Sdo7m4g',
    appId: '1:733817369426:ios:3a7e8ab58206972fc6008b',
    messagingSenderId: '733817369426',
    projectId: 'store-app-42487',
    storageBucket: 'store-app-42487.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF37L45QGvIQVvTvqdf44KpDAFbWAwhNM',
    appId: '1:733817369426:web:d9520bdca201fb3bc6008b',
    messagingSenderId: '733817369426',
    projectId: 'store-app-42487',
    authDomain: 'store-app-42487.firebaseapp.com',
    storageBucket: 'store-app-42487.appspot.com',
    measurementId: 'G-9W9ZPW642F',
  );
}
